version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-security
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.0.13
    container_name: mongodb-security
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rest_tutorial
    ports:
      - "27017:27017"